[package]
name = "rust-fuzzer-gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "2.0.0", features = ["full", "visit-mut"] }
quote = "1.0"
walkdir = "2"
proc-macro2 = "1"
